### ISSUE TITLE
Recipe 6 error

### ISSUE THREAD

**Issue by ghost** [driscollis/wxPython_recipes_book_code#1]
```
Traceback (most recent call last):
  File "main.py", line 48, in onToggleDark
    dark_mode.darkMode(self, self.defaultColor)
  File "C:\Users\bach_ar\Desktop\wxpython-recipes-master\wxpythoncookbookcode-master\recipe_6_dark_mode\dark_mode.py", line 56, in darkMode
    if isinstance(widget, ObjectListView) or isinstance(widget, wx.ListCtrl):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by driscollis** [comment]
I am assuming you got this from the wxPython Cookbook version of the book and not from this repository? This code is now in Chapter 3 here: https://github.com/driscollis/wxPython_recipes_book_code/tree/master/chapter_3_special_effects/recipe_3_2_dark_mode

I just tried running it with Python 3.6 and wxPython 4.0.0b2 and it worked without any exceptions. Can you try the code linked above and let me know if it works? If it does not work, please let me know what version of Python, wxPython and OS you are using.

**Comment by ghost** [comment]
Hello Mike,

 

the code you refered in your mail leads to a different error on both Python 2 and 3:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import dark_mode
  File "C:\Users\bach_ar\Desktop\wxpython-recipes-master\wxpythoncookbookcode-master\recipe_6_dark_mode\dfg\dark_mode.py", line 3, in <module>
    from ObjectListView import ObjectListView
ModuleNotFoundError: No module named 'ObjectListView'

 

My original error report was at least showing the GUI, but getting the error about isinstance requiring a tuple on clicking the button for dark mode.

Hope that helps!

 

Cheers,

Arne

 

Gesendet: Donnerstag, 04. Januar 2018 um 18:42 Uhr
Von: "Mike Driscoll" <notifications@github.com>
An: driscollis/wxPython_recipes_book_code <wxPython_recipes_book_code@noreply.github.com>
Cc: "Arne Bachmann" <arne.bachmann@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [driscollis/wxPython_recipes_book_code] Recipe 6 error (#1)


I am assuming you got this from the wxPython Cookbook version of the book and not from this repository? This code is now in Chapter 3 here: https://github.com/driscollis/wxPython_recipes_book_code/tree/master/chapter_3_special_effects/recipe_3_2_dark_mode

I just tried running it with Python 3.6 and wxPython 4.0.0b2 and it worked without any exceptions. Can you try the code linked above and let me know if it works? If it does not work, please let me know what version of Python, wxPython and OS you are using.

**Comment by driscollis** [comment]
Strange. You do need ObjectListView installed for the code to work, but you should have already had that installed for the original version too. Either way, you can install it with pip:

`pip install objectlistview`

Or download it here: https://pypi.python.org/pypi/ObjectListView

**Comment by ghost** [comment]
Thanks!

That solved it in both versions.

Didn´t know about this dependency, and it wasn´t installed automatically by wx.

 

Cheers

Arne

 

Gesendet: Montag, 08. Januar 2018 um 15:24 Uhr
Von: "Mike Driscoll" <notifications@github.com>
An: driscollis/wxPython_recipes_book_code <wxPython_recipes_book_code@noreply.github.com>
Cc: "Arne Bachmann" <arne.bachmann@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [driscollis/wxPython_recipes_book_code] Recipe 6 error (#1)


Strange. You do need ObjectListView installed for the code to work, but you should have already had that installed for the original version too. Either way, you can install it with pip:

pip install objectlistview

Or download it here: https://pypi.python.org/pypi/ObjectListView

**Comment by driscollis** [comment]
Yeah, it's a 3rd party widget. It looks like I updated that chapter in the wxPython Recipes version of the book, but I failed to mention that in the original wxPython Cookbook. Sorry about that. Glad we got it sorted out though.
